#───────────────────────────────────────────────────────────────────────────────
# Description:
#───────────────────────────────────────────────────────────────────────────────
# Dashboard designed for viewing on tablet and optimized for 1280x800 screen
# resolutions. Appearance may be different on other screen resolutions.
#
# The main dashboard is designed with a custom header (default header is hidden
# using kiosk mode) and three columns.
#
# Custom popup dialog boxes are used to display information and control various
# smart home devices.
#
#───────────────────────────────────────────────────────────────────────────────
# Custom components required:
#───────────────────────────────────────────────────────────────────────────────
# Kiosk-mode:   https://github.com/maykar/kiosk-mode
# Browser-mod:  https://github.com/thomasloven/hass-browser_mod
#
# Additional custom cards are used for some of the cards included below

################################################################################
###                    Kiosk mode - hide default HA header                   ###
################################################################################
kiosk_mode:
  hide_header: true

################################################################################
###                   Custom button card styling templates                   ###
################################################################################
button_card_templates: !include include/cards/button_card_templates.yaml

views:
  ##############################################################################
  ###                          FRONT PAGE VIEW                               ###
  ##############################################################################
  - icon: mdi:home
    title: Home
    #───────────────────────────────────────────────────────────────────────────
    # Render dashboard in full-width. See more in HA documentation:
    # https://www.home-assistant.io/lovelace/dashboards-and-views#panel
    #───────────────────────────────────────────────────────────────────────────
    panel: true
    ############################################################################
    ###       Popup card configuration for browser_mod custom component      ###
    ############################################################################
    popup_cards:
      #─────────────────────────────────────────────────────────────────────────
      # Weather forcast - next 48 hours
      #─────────────────────────────────────────────────────────────────────────
      weather.hjem:
        title: Weather forecast for the next 48 hours
        large: true
        card: !include include/cards/local_weather_popup.yaml
      #─────────────────────────────────────────────────────────────────────────
      # Garbage collection dates
      #─────────────────────────────────────────────────────────────────────────
      calendar.garbage_collection:
        title: Garbage collection
        card: !include include/cards/garbage_collection.yaml
      #─────────────────────────────────────────────────────────────────────────
      # Today's recipe and weekly food plan
      #─────────────────────────────────────────────────────────────────────────
      sensor.madplan_dagensret:
        title: Today's recipe
        large: true
        card:
          type: iframe
          url: !secret madplan_dagensret_url
      dummy.madplan:
        title: Madplan
        large: true
        card:
          type: iframe
          url: !secret madplan_ugeplan_url
      #─────────────────────────────────────────────────────────────────────────
      # Shopping list
      #─────────────────────────────────────────────────────────────────────────
      sensor.our_groceries:
        title: Shopping list
        large: true
        card: !include include/cards/shopping_list.yaml
      #─────────────────────────────────────────────────────────────────────────
      # TODO list
      #─────────────────────────────────────────────────────────────────────────
      dummy.TODO:
        title: Tasks
        large: true
        card:
          type: shopping-list
      #─────────────────────────────────────────────────────────────────────────
      # Last motion and door open events
      #─────────────────────────────────────────────────────────────────────────
      sensor.last_door_sensor:
        title: Recent events
        large: true
        card: !include include/cards/event_log.yaml
      sensor.last_motion_sensor:
        title: Recent motion
        large: true
        card: !include include/cards/event_log.yaml
      #─────────────────────────────────────────────────────────────────────────
      # Home state selection
      #─────────────────────────────────────────────────────────────────────────
      input_select.home_state:
        title: Select home state
        large: true
        card: !include include/cards/home_state_selection.yaml
    cards:
      - type: vertical-stack
        cards:
          ######################################################################
          ###                          Header row                            ###
          ######################################################################
          - type: horizontal-stack
            cards:
              - !include include/cards/tablet_header.yaml
          ######################################################################
          ###                   Main content - 3 columns                     ###
          ######################################################################
          - type: horizontal-stack
            cards:
              ##################################################################
              ###                         Column #1                          ###
              ##################################################################
              - type: vertical-stack
                cards:
                  #─────────────────────────────────────────────────────────────
                  # Today's receipe
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/todays_recipe.yaml
                  #─────────────────────────────────────────────────────────────
                  # Choose between calendar, shopping list, TODO list or
                  # garbage collection information
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/info_select.yaml
                  #─────────────────────────────────────────────────────────────
                  # Custom calendar card
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/calendar_week.yaml

              ##################################################################
              ####                        Column #2                          ###
              ##################################################################
              - type: vertical-stack
                cards:
                  #─────────────────────────────────────────────────────────────
                  # Light scene selection
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/light_scene_selection.yaml
                  #─────────────────────────────────────────────────────────────
                  # Mini media player
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/media_player_kitchen.yaml
                  #─────────────────────────────────────────────────────────────
                  # IP camera feed
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/camera_feed01.yaml
                  #─────────────────────────────────────────────────────────────
                  # Status
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/home_status_events.yaml

              ##################################################################
              ####                        Column #3                          ###
              ##################################################################
              - type: vertical-stack
                cards:
                  #─────────────────────────────────────────────────────────────
                  # Weather forecast from Met.no integration
                  #─────────────────────────────────────────────────────────────
                  - type: weather-forecast
                    entity: weather.hjem
                    name: Weather forecast
                  #─────────────────────────────────────────────────────────────
                  # Current weather data from Netatmo Weather Station and
                  # indoor temperature sensors
                  #─────────────────────────────────────────────────────────────
                  - !include include/cards/local_weather.yaml

  ##############################################################################
  ### 01                           VW INFO VIEW                              ###
  ##############################################################################
  - !include include/views/vw_info.yaml

  ##############################################################################
  ### 02                       VACUUM CONTROL VIEW                           ###
  ##############################################################################
  - !include include/views/vacuum_control.yaml

  ##############################################################################
  ### 03                         FLOORPLAN VIEW                              ###
  ##############################################################################
  - !include include/views/floorplan.yaml

  ##############################################################################
  ### 04                            MUSIC VIEW                               ###
  ##############################################################################
  - !include include/views/music2.yaml

  ##############################################################################
  ### 05                     CUSTOM ENERGY DASHBOARD                         ###
  ##############################################################################
  - !include include/views/energy.yaml

title: " "
